source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '~> 4.1'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'coffee-rails'
gem 'rails-assets-angular-resource'
gem 'rails-assets-angular'
gem 'rails-assets-restangular'
gem 'rails-assets-angular-ui-select'
gem 'angular-ui-bootstrap-rails'
gem 'lodash-rails'
gem 'sass-rails', '>= 4.0.4'
gem 'jquery-rails'
gem 'mysql2'
gem 'rails-assets-angular-datatables'
gem 'crack'
gem 'plissken'
gem 'activerecord-import'

group :development, :test do
  gem 'teaspoon'
  gem 'phantomjs'
  gem 'guard'
  gem 'guard-teaspoon'
  gem 'sqlite3'
  gem 'rubocop'
  gem 'rmre'

end