# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5eef338a1cae3a59301e8eeeb85222f3396ab5e702f9c8f07ed15e4f2e5a6bde3bd9f5516baf42ab02b2e48dc3b61caed7231c0a9fb2540600671dfb4ffc415

test:
  secret_key_base: 12acd1dd0046aadeb553efdb5f374709cce568c383a88443eb6143c5f58545b16059f5a78b47b964d864113b4b29e608c2aa5d78e70c1acb688504778cb665dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
